// <auto-generated />
using System;
using CreditCalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditCalculator.Migrations
{
    [DbContext(typeof(CreditCalculatorContext))]
    [Migration("20220628180148_test3")]
    partial class test3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CreditCalculator.Models.CreditCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MonthlyTerm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CreditCalculations");
                });

            modelBuilder.Entity("CreditCalculator.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("BodySum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreditCalculationId")
                        .HasColumnType("int");

                    b.Property<decimal>("DebtBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MarginSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreditCalculationId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("CreditCalculator.Models.Payment", b =>
                {
                    b.HasOne("CreditCalculator.Models.CreditCalculation", null)
                        .WithMany("Payments")
                        .HasForeignKey("CreditCalculationId");
                });

            modelBuilder.Entity("CreditCalculator.Models.CreditCalculation", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
